### ISSUE TITLE
Parsing not picking up names with "_"

### ISSUE THREAD

**Issue by jorge-barroso** [cbrand/go-filterparams#5]
Using go 1.15 and this library on version v0.0.0-20210107124740-64b77ab96ef4 (taken from go.mod)
On Linux

The sample file I'm working on is attached as a text file so that Github can accept it. It basically works as it stands and picks the alias correctly, but if I change anything inside a square bracket so that it contains "_" it will be ignored
Two examples are the alias, changing "introducername" or "agreementnumber" to introducer_name or "agreement_number" will get them ignored

[test_go_filterparams.txt](https://github.com/cbrand/go-filterparams/files/5951799/test_go_filterparams.txt)

**Comment by cbrand** [comment]
Hi
Thank you for the bug report. I added a unit test according to the example you provided and you are right, the library didn't support `_` in the parameter name.

I added support for it and the following code works now as expected:

```go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/url"

	"github.com/cbrand/go-filterparams"
	filter "github.com/cbrand/go-filterparams/definition"
)

func GetFilterArguments(toParseURL *url.URL) (*filterparams.QueryData, error) {
	builder := filterparams.NewBuilder()
	builder.EnableFilter(filter.FilterEq)
	builder.EnableFilter(filter.FilterLike)
	query := builder.CreateQuery()

	values := toParseURL.Query()
	return query.Parse(&values)
}

func main() {
	urlTemplate := "http://myurl.com?filter[param][reference][eq][introducer_name]=%s&filter[param][references][eq][agreement_number]=%s"
	urlString := fmt.Sprintf(urlTemplate, url.QueryEscape("Broker 1"), url.QueryEscape("123456789"))
	log.Print(urlString)
	url, _ := url.Parse(urlString)
	query, err := GetFilterArguments(url)
	if err != nil {
		log.Print(err.Error())
	} else {
		data, _ := json.Marshal(query.GetFilter())
		log.Print(string(data))
	}
}
```

Can you check again?

**Comment by cbrand** [comment]
For reference according unit test: https://github.com/cbrand/go-filterparams/blob/637d631396af24b77330e548f11f1752a068a0a0/query_test.go#L26-L49

**Comment by cbrand** [comment]
Closing this for now. Feel free to reopen it if you face the issue with the newest version again.
